---
# YAML 1.2
# See: http://yaml.org for more info.  EXP uses the yaml-cpp library
# (http://github.com/jbeder/yaml-cpp) for parsing and emitting YAML
#
# ------------------------------------------------------------------------
# These parameters control the simulation
# ------------------------------------------------------------------------
Global:
  outdir     : data
  nthrds     : 1
  dtime      : 0.002
  ldlibdir   : /usr/local/EXP/lib/user
  runtag     : run0
  nsteps     : 1000
  multistep  : 0
  dynfracV   : 0.01
  dynfracA   : 1.0e30
  dynfracP   : 1.0e30
  dynfracD   : 0.05
  infile     : OUT.run0.chkpt
  VERBOSE    : 4

# ------------------------------------------------------------------------
# This is a sequence of components.  The parameters for the force are
# now included as a parameter map, rather than a separate file.
#
# Each indented stanza beginning with '-' is a component
# ------------------------------------------------------------------------
Components:
  - name       : cube
    parameters : {nlevel: 1, indexing: true}
    bodyfile   : cube.bods
    force :
      id : cube
      parameters :
        nmaxx : 8
        nmaxy : 8
        nmaxz : 8
        
# ------------------------------------------------------------------------
# This is a sequence of outputs
# ------------------------------------------------------------------------
Output:
  - id : outlog
    parameters : {nint: 10}
  - id : outpsn
    parameters : {nint: 1000}
  - id : outchkpt
    parameters : {nint: 200}
  - id: outcoef
    parameters : {nint: 1, name: cube}

# ------------------------------------------------------------------------
# This is a sequence of external forces
# This can be empty (or missing)
# ------------------------------------------------------------------------
External:
  - id : PeriodicBC
    parameters : {sx: 1, sy: 1, sz: 1, cx: 0, cy: 0, cz: 0, compname: cube}

# Currently empty

# ------------------------------------------------------------------------
# List of interations as name1 : name2 map entries
# This can be empty (or missing).  By default, all components will
# interact unless interactions are listed below.  This behavior can
# be inverted using the 'allcouples: false' flag in the 'Global' map
# ------------------------------------------------------------------------
Interaction:

# None: only one component

...
